### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by superdav42** [flathub/net.lutris.Lutris#122]
Runing latest lutris from flatpak I can't get any games to launch. Here's the output of the console.
```
Unable to load locale dir, translations won't work.
2020-10-29 21:19:02,432: Couldn't find a terminal emulator.
2020-10-29 21:19:02,592: MAME XML generation launched in the background, not returning anything this time
2020-10-29 21:19:02,592: Getting full game list from MAME...
2020-10-29 21:19:02,593: MAME isn't installed, can't retrieve systems list.
Gtk-Message: 21:19:02.687: Failed to load module "canberra-gtk-module"
2020-10-29 21:19:02,690: Running Lutris 0.5.7.1
2020-10-29 21:19:02,690: Using Intel Open Source Technology Center
2020-10-29 21:19:02,690: Running Mesa driver 20.1.5 on Mesa DRI Intel(R) HD Graphics 5500 (BDW GT2) (0x1616)
2020-10-29 21:19:02,690: GPU: 8086:1616 17AA:503E using i915 drivers
2020-10-29 21:19:02,767: Vulkan is supported
2020-10-29 21:19:03,360: MAME XML written
2020-10-29 21:22:22,505: The game doesn't have an executable
lutris-wrapper: /sysroot/home/james/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-5.7-11-x86_64/bin/winecfg
Running /sysroot/home/james/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-5.7-11-x86_64/bin/winecfg
Initial process has started with pid 29
Game is considered started.
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 0
2020-10-29 21:22:38,595: Creating a win32 prefix in /sysroot/home/james/Games/pokemon-tcg-online
2020-10-29 21:22:55,324: win32 Prefix created in /sysroot/home/james/Games/pokemon-tcg-online
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/lutris/exceptions.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/lutris/game.py", line 314, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 611, in get_config
    return [logical_monitor.get_config() for logical_monitor in self.display_config.current_state.logical_monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 611, in <listcomp>
    return [logical_monitor.get_config() for logical_monitor in self.display_config.current_state.logical_monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 372, in get_config
    monitors = [(monitor.name, monitor.get_current_mode().id) for monitor in self.monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 372, in <listcomp>
    monitors = [(monitor.name, monitor.get_current_mode().id) for monitor in self.monitors]
AttributeError: 'NoneType' object has no attribute 'id'
2020-10-29 21:29:09,225: Runtime disabled by system configuration
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/lutris/exceptions.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/lutris/game.py", line 314, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 611, in get_config
    return [logical_monitor.get_config() for logical_monitor in self.display_config.current_state.logical_monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 611, in <listcomp>
    return [logical_monitor.get_config() for logical_monitor in self.display_config.current_state.logical_monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 372, in get_config
    monitors = [(monitor.name, monitor.get_current_mode().id) for monitor in self.monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 372, in <listcomp>
    monitors = [(monitor.name, monitor.get_current_mode().id) for monitor in self.monitors]
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/lutris/exceptions.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/lutris/game.py", line 314, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 611, in get_config
    return [logical_monitor.get_config() for logical_monitor in self.display_config.current_state.logical_monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 611, in <listcomp>
    return [logical_monitor.get_config() for logical_monitor in self.display_config.current_state.logical_monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 372, in get_config
    monitors = [(monitor.name, monitor.get_current_mode().id) for monitor in self.monitors]
  File "/app/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 372, in <listcomp>
    monitors = [(monitor.name, monitor.get_current_mode().id) for monitor in self.monitors]
AttributeError: 'NoneType' object has no attribute 'id'
```
Any advise on how to get it working?

**Comment by A6GibKm** [comment]
Are you using multiple monitors?

**Comment by superdav42** [comment]
> Are you using multiple monitors?

Nope, just a single laptop monitor. Nothing too unusual except it is on Endless OS which is not very common.

**Comment by superdav42** [comment]
I got it working by updating and reinstalling lots of things. Don't remember exactly but we can close this.
