### ISSUE TITLE
No Terminal Emulator

### ISSUE THREAD

**Issue by kleinermob** [flathub/net.lutris.Lutris#141]
when trying to run "Open Bash terminal" lutris says: 
2021-01-21 12:10:23,920: Couldn't find a terminal emulator.

**Comment by LosEagle** [comment]
can confirm

**Comment by A6GibKm** [comment]
This error has been present for a long time and should not be a cause for init failures.

**Comment by alvarlagerlof** [comment]
I'm getting this too in addition to it not finding a dxvk_versions.json file:

```
2021-01-27 15:27:05,610: Couldn't find a terminal emulator.
Traceback (most recent call last):
  File "/app/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/app/lib/python3.8/site-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/app/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/app/lib/python3.8/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/app/lib/python3.8/site-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/app/lib/python3.8/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/app/lib/python3.8/site-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/app/lib/python3.8/site-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/app/lib/python3.8/site-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/app/lib/python3.8/site-packages/lutris/util/wine/dxvk.py", line 65, in load_dxvk_versions
    with open(versions_path, "r") as dxvk_version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alvar/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk_versions.json'
```

**Comment by A6GibKm** [comment]
Did you check the readme? There are a plethora of bugs all related to not having the correct compact extension, run (with or without --user)

```
flatpak install --user flathub org.gnome.Platform.Compat.i386//3.38
```

**Comment by Rajalolxd** [comment]
> I'm getting this too in addition to it not finding a dxvk_versions.json file:
Try this
wget https://cdn.discordapp.com/attachments/538903130704838656/796102070825779250/dxvk_versions.json -P $HOME/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk

https://forums.lutris.net/t/lutris-doesnt-start-on-ubuntu-lts/11556/2

worked for me

**Comment by nickavem** [comment]
To my knowledge there is no portal for opening terminal emulators. We could try building `gnome-terminal` in the package, or even just a super simple vte build. I'll look into it.

**Comment by Baturax** [comment]
could you add foot terminal
