### ISSUE TITLE
Can't open Winetricks

### ISSUE THREAD

**Issue by okseb** [flathub/net.lutris.Lutris#190]
Winetricks is not opening and seems to be due to missing zenity.

![Screenshot from 2021-10-10 22-33-31](https://user-images.githubusercontent.com/13012832/136725282-10ccdfe3-70ec-4d70-86cd-e10d5e8ffccf.png)

**Comment by strycore** [comment]
Zenity needs to be added to the flatpak

**Comment by A6GibKm** [comment]
@strycore we bundle zenity, but after testing I am getting
```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/lutris/gui/widgets/game_bar.py", line 264, in on_link_button_clicked
    callback(button)
  File "/app/lib/python3.9/site-packages/lutris/runners/wine.py", line 701, in run_winetricks
    winetricks(
  File "/app/lib/python3.9/site-packages/lutris/runners/commands/wine.py", line 346, in winetricks
    return wineexec(
  File "/app/lib/python3.9/site-packages/lutris/runners/commands/wine.py", line 299, in wineexec
    wine.prelaunch()
  File "/app/lib/python3.9/site-packages/lutris/runners/wine.py", line 791, in prelaunch
    create_prefix(self.prefix_path, wine_path=self.get_executable(), arch=self.wine_arch)
  File "/app/lib/python3.9/site-packages/lutris/runners/commands/wine.py", line 105, in create_prefix
    os.rmdir(prefix)
OSError: [Errno 16] Device or resource busy: '/var/home/user/.wine'
```
Naturally, `~/.wine` is outside the sandbox permissions of the flatpak, but I think this should be pointing towards the actual wine prefix used by the game at `~/Games/...`.

By giving the flatpak access to home, I am able to run winetricks, but I am not sure if this `.wine` folder is right. I also noticed that this wine prefix is created on the main thread (which blocks the UI thread), I could try sending a patch to do this in a thread later.

**Comment by strycore** [comment]
Lutris never uses ~/.wine unless something is configured wrong. We don't need access to the host's version of this folder.

**Comment by A6GibKm** [comment]
After adding `--filesystem=home` winetricks opens but the CLI output says
```
2022-04-06 18:39:29,400: No valid prefix detected in /var/home/user/.wine, creating one...
2022-04-06 18:39:29,488: Creating a win64 prefix in /var/home/user/.wine
```

**Comment by strycore** [comment]
Do you have a way to reproduce that? Winetricks calls should be executed in the context of a game. Here the prefix is created by Lutris, which means the game doesn't have a prefix set?

**Comment by A6GibKm** [comment]
Everything about the game prefix looks ok, ill try reproducing with a clean install as my config is old and from before we had home access

**Comment by FilBot3** [comment]
@A6GibKm , did you do any custom configurations to your Lutris System Configs? Like, changed where games go, or where runners are installed?

**Comment by A6GibKm** [comment]
> @A6GibKm , did you do any custom configurations to your Lutris System Configs? Like, changed where games go, or where runners are installed?

Nope. I use lutris as vanilla as possible.

**Comment by motorto** [comment]
```
2023-02-01 21:35:31,310: Unable to load libGLX_nvidia.so.0
2023-02-01 21:35:31,310: Unable to locate libGLX_nvidia
2023-02-01 21:35:31,328: Invalid override value disable
2023-02-01 21:35:31,328: Invalid override value disable
2023-02-01 21:35:31,328: Invalid override value disable
2023-02-01 21:35:31,332: Invalid override value disable
2023-02-01 21:35:31,332: Invalid override value disable
2023-02-01 21:35:31,333: Invalid override value disable
2023-02-01 21:35:31,404: Unable to load libGLX_nvidia.so.0
2023-02-01 21:35:31,404: Unable to locate libGLX_nvidia
Started initial process 2140 from /var/home/cerqueira/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks --unattended
Start monitoring process.
wget: symbol lookup error: /usr/lib/x86_64-linux-gnu/libassuan.so.0: undefined symbol: gpgrt_malloc, version GPG_ERROR_1.0
------------------------------------------------------
warning: Github down? version '' doesn't appear to be a valid version
------------------------------------------------------
Executing mkdir -p /var/home/cerqueira/Games
Using winetricks 20220411-next - sha256sum: 50b745d7f46ead56fd0c9e6d753d53ea0ae368c988434c25d65fec66307e5d4f with wine-7.2-1-g1f8837bdccd (Staging) and WINEARCH=win32
zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0: undefined symbol: atk_component_scroll_to
winetricks GUI enabled, using zenity 
zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0: undefined symbol: atk_component_scroll_to
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
```

This is what I am getting on my system (it is different of all the logs posted here)

**Comment by LukeShortCloud** [comment]
@strycore Do you know how this can be fixed? Both `wget` and `zenity` are having issues in the Flatpak.

- https://github.com/flathub/net.lutris.Lutris/issues/190#issuecomment-1412764051
- https://github.com/lutris/lutris/issues/6144

**Comment by legluondunet** [comment]
I can not reproduce this issue, is this only happened with Bazzite Linux distribution?

**Comment by legluondunet** [comment]
can not reproduce
