### ISSUE TITLE
Steam shortcuts can't be created

### ISSUE THREAD

**Issue by strycore** [flathub/net.lutris.Lutris#238]
```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/lutris/game_actions.py", line 298, in on_create_steam_shortcut
    steam_shortcut.update_shortcut(self.game)
  File "/app/lib/python3.9/site-packages/lutris/util/steam/shortcut.py", line 72, in update_shortcut
    create_shortcut(game, shortcut_path)
  File "/app/lib/python3.9/site-packages/lutris/util/steam/shortcut.py", line 90, in create_shortcut
    with open(shortcut_path, "wb") as shortcut_file:
OSError: [Errno 30] Read-only file system: '/home/deck/.local/share/Steam/userdata/10042493/config/shortcuts.vdf'
```

**Comment by A6GibKm** [comment]
Could you test this with --filesystem=home?

**Comment by A6GibKm** [comment]
What do you mean by shortcut? is this a `ln` or a desktop file? there is a new xdg portal for the later.

**Comment by strycore** [comment]
No I don't mean a desktop shortcut, I mean a non Steam game inside of Steam, Lutris is trying to write to '/home/deck/.local/share/Steam/userdata/10042493/config/shortcuts.vdf' but the steam files are read only

**Comment by strycore** [comment]
Fixed by giving home access
