### ISSUE TITLE
Lutris Flatpak unable to find system installed Xephyr

### ISSUE THREAD

**Issue by OlivierGagnon** [flathub/net.lutris.Lutris#276]
Hello, I have Xephyr installed locally, but when I use it in a prefix, it is unable to find the exe.

I've tried going into Flatseal and giving it lots of permission to my local filesystem but it still can't find it

Thanks!

2022-06-22 15:26:54,434: EV Nova (wine) has encountered an error: Unable to find Xephyr, install it or disable the Xephyr option
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/lutris/exceptions.py", line 56, in wrapper
    return function(*args, **kwargs)
  File "/app/lib/python3.9/site-packages/lutris/game.py", line 503, in configure_game
    env["DISPLAY"] = self.start_xephyr()
  File "/app/lib/python3.9/site-packages/lutris/game.py", line 342, in start_xephyr
    raise GameConfigError(_("Unable to find Xephyr, install it or disable the Xephyr option"))
lutris.exceptions.GameConfigError: Unable to find Xephyr, install it or disable the Xephyr option
2022-06-22 15:27:00,842: Shutting down Lutris
(deck@steamdeck ~)$ which Xephyr 
/usr/bin/Xephyr

**Comment by OlivierGagnon** [comment]
Yep it worked! thx
