### ISSUE TITLE
Doesn't work with runtime 45

### ISSUE THREAD

**Issue by xordspar0** [flathub/net.lutris.Lutris#372]
Lutris fails to start with runtime 45, which it started using in 55259e9d5b1a26bd9e765ab0d155ad2a93f94305.

```
$ flatpak run net.lutris.Lutris
2023-10-14 12:22:35,765: Command /app/bin/lspci after 3 seconds
Traceback (most recent call last):
  File "/app/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/app/lib/python3.11/site-packages/lutris/game.py", line 24, in <module>
    from lutris.runners.wine import get_wine_version
  File "/app/lib/python3.11/site-packages/lutris/runners/wine.py", line 25, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/app/lib/python3.11/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/var/home/jordan/.local/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/var/home/jordan/.local/lib/python3.11/site-packages/PIL/__init__.py)
```

**Comment by strycore** [comment]
You have python packages installed locally which interfere with Lutris.

To fix the issue run: 

sudo rm -rf /var/home/jordan/.local/lib/

**Comment by strycore** [comment]
It's super weird that the behavior of Lutris is disturbed by packages installed on the host. But that's the cost of having full access to the home folder.

At some point we should prevent Lutris from loading modules from ~/.local/share/lib

**Comment by strycore** [comment]
I added a patch to prevent Lutris loading modules from /home, but it may need /var/home as well for the Flatpak

https://github.com/lutris/lutris/commit/be2c47cb4baafba8d7a4a8148ea41ae39e72ce9e

**Comment by xordspar0** [comment]
Oh wow, that is not what I expected the problem to be. Thanks!

**Comment by A6GibKm** [comment]
And this is certainly something I didn't think possible either
