### ISSUE TITLE
Not launching on nixos

### ISSUE THREAD

**Issue by anoosa1** [flathub/net.lutris.Lutris#435]
Try to launch the program and errors out

lutirs native works

logs
```
2024-09-21 18:57:55,890: Command 'fluidsynth' not found on your system
/app/lib/python3.11/site-packages/PIL/Image.py:121: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.2.0
Pillow version: 9.5.0
  warnings.warn(str(v), RuntimeWarning)
/app/lib/python3.11/site-packages/PIL/Image.py:121: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.2.0
Pillow version: 9.5.0
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "/app/bin/lutris", line 61, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 42, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/app/lib/python3.11/site-packages/lutris/gui/config/preferences_dialog.py", line 9, in <module>
    from lutris.gui.config.accounts_box import AccountsBox
  File "/app/lib/python3.11/site-packages/lutris/gui/config/accounts_box.py", line 8, in <module>
    from lutris.gui.config.updates_box import UpdateButtonBox
  File "/app/lib/python3.11/site-packages/lutris/gui/config/updates_box.py", line 12, in <module>
    from lutris.services.lutris import sync_media
  File "/app/lib/python3.11/site-packages/lutris/services/__init__.py", line 8, in <module>
    from lutris.services.dolphin import DolphinService
  File "/app/lib/python3.11/site-packages/lutris/services/dolphin.py", line 6, in <module>
    from PIL import Image
  File "/app/lib/python3.11/site-packages/PIL/Image.py", line 103, in <module>
    raise ImportError(
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 9.2.0
Pillow version: 9.5.0
```

flatpak --version
Flatpak 1.14.6

flatpak --gl-drivers
default
host

**Comment by strycore** [comment]
Please try  the updated version I just pushed on Flathub Beta (it should be building right now so check about 2 hours after this comment)

**Comment by anoosa1** [comment]
Still persists

**Comment by dreua** [comment]
Check your environment, I bet it contains a `PYTHONPYCACHEPREFIX` variable. Try unsetting it for the flatpak launch.

**Comment by dreua** [comment]
What was the solution?

I got a patch merged to ignore pythoncacheprefix when running flatpaks but it hasn't been released yet. https://github.com/flatpak/flatpak/pull/6110
