### ISSUE TITLE
"locale.Error: unsupported locale setting" when Running Lutris Flatpak

### ISSUE THREAD

**Issue by june128** [flathub/net.lutris.Lutris#78]
When I start the Lutris flatpak using `flatpak run net.lutris.Lutris` I get the following error:

```
Traceback (most recent call last):
  File "/app/bin/lutris", line 27, in <module>
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

My locale is (retrieved using the `locale` command):

```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

I would've suspected that this is an issue of the Lutris application itself, but if I start the Lutris installed via my package manager, I don't encounter this issue.

I can also circumvent this error by running the Lutris flatpak using the following command: ` env LC_ALL=en_US.UTF-8 flatpak run net.lutris.Lutris`, but that's not a great solution.

**Comment by gasinvein** [comment]
Does running `flatpak update --subpath=de org.gnome.Platform.Locale` prior to launching Lutris help?

**Comment by julianschacher** [comment]
Yup, that fixed my issue. Thanks!

**Comment by gasinvein** [comment]
This doesn't look like something specific to Lutris to me. Maybe report it to https://github.com/flatpak/flatpak/issues?

**Comment by julianschacher** [comment]
I'll validate the issue with another app using `org.gnome.Platform.Locale` and then report it there.

**Comment by dreua** [comment]
I'm experiencing the same trying to create a flatpak of jeromerobert/pdfarranger#37. Also python based and my locale is also a mix of en_US and de_DE, workaround works but I'd like to have this fixed for users. It would be great if someone with more background knowledge of flatpak could report this.

**Comment by A6GibKm** [comment]
Note that upstream has
```
try:
    locale.setlocale(locale.LC_ALL, "")
except locale.Error:
    sys.stderr.write("Unsupported locale setting. Fix your locales\n")
```
idk if this is ok nor if it is related.
