### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by FakeShemp** [flathub/net.lutris.Lutris#97]
```
2020-03-30 13:42:13,273: Package 'distro' unavailable. Unable to read Linux distribution
Traceback (most recent call last):
  File "/app/bin/lutris", line 34, in <module>
    from lutris.gui.application import Application
  File "/app/lib/python3.7/site-packages/lutris/gui/application.py", line 35, in <module>
    from lutris.game import Game
  File "/app/lib/python3.7/site-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/app/lib/python3.7/site-packages/lutris/runners/wine.py", line 11, in <module>
    from lutris.runners.runner import Runner
  File "/app/lib/python3.7/site-packages/lutris/runners/runner.py", line 7, in <module>
    from lutris.config import LutrisConfig
  File "/app/lib/python3.7/site-packages/lutris/config.py", line 6, in <module>
    from lutris import settings, sysoptions
  File "/app/lib/python3.7/site-packages/lutris/sysoptions.py", line 9, in <module>
    from lutris.util.display import USE_DRI_PRIME, DISPLAY_MANAGER
  File "/app/lib/python3.7/site-packages/lutris/util/display.py", line 4, in <module>
    from dbus.exceptions import DBusException
ModuleNotFoundError: No module named 'dbus'
```

**Comment by gasinvein** [comment]
And people are [asking](https://github.com/flathub/net.lutris.Lutris/issues/38#issuecomment-551887544) about stable release. I guess it's not going to ever be stable as long as @LeandroStanger keeps blindly pushing untested updates, breaking it.

**Comment by AsciiWolf** [comment]
I usually test all PRs by @LeandroStanger (and other people) in my Flatpak repos before merging them.

**Comment by gasinvein** [comment]
@AsciiWolf He has push perms to this repo anyway.

**Comment by AsciiWolf** [comment]
@gasinvein Ah! Then he should test his PRs before merging them. :-)
